In [55]:
import pandas as pd
import numpy as np
from src import soporte_limpieza as sl

In [2]:
pd.set_option("display.max_columns", None)

In [17]:
df_2013 = pd.read_csv("../11.Proyecto2_EDA-Ingresos-Publicos-Brasil/datos/datos-2013_limpio.csv", encoding='latin-1')

df_2014 = pd.read_csv("../11.Proyecto2_EDA-Ingresos-Publicos-Brasil/datos/datos-2014_limpio.csv", encoding='latin-1')

df_2015 = pd.read_csv("../11.Proyecto2_EDA-Ingresos-Publicos-Brasil/datos/datos-2015_limpio.csv", encoding='latin-1')

df_2016 = pd.read_csv("../11.Proyecto2_EDA-Ingresos-Publicos-Brasil/datos/datos-2016_limpio.csv", encoding='latin-1')

df_2017 = pd.read_csv("../11.Proyecto2_EDA-Ingresos-Publicos-Brasil/datos/datos-2017_limpio.csv", encoding='latin-1')

df_2018 = pd.read_csv("../11.Proyecto2_EDA-Ingresos-Publicos-Brasil/datos/datos-2018_limpio.csv", encoding='latin-1')

df_2019 = pd.read_csv("../11.Proyecto2_EDA-Ingresos-Publicos-Brasil/datos/datos-2019_limpio.csv", encoding='latin-1')

df_2020 = pd.read_csv("../11.Proyecto2_EDA-Ingresos-Publicos-Brasil/datos/datos-2020_limpio.csv", encoding='latin-1')

df_2021 = pd.read_csv("../11.Proyecto2_EDA-Ingresos-Publicos-Brasil/datos/datos-2021_limpio.csv", encoding='latin-1')

In [19]:
df = pd.concat([df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021], axis= 0)
df.head(2)

,NOMBRE ÓRGANO SUPERIOR,CÓDIGO ÓRGANO,NOMBRE ÓRGANO,CÓDIGO UNIDAD GESTORA,NOMBRE UNIDAD GESTORA,CATEGORÍA ECONÓMICA,ORIGEN INGRESO,TIPO INGRESO,DETALLE,VALOR PREVISTO ACTUALIZADO,VALOR LANZADO,VALOR REALIZADO,PORCENTAJE REALIZADO,FECHA LANZAMIENTO,AÑO EJERCICIO
0,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com víncul...,110060,COORD. GERAL DE ORC. FIN. E ANAL. CONT. - AGU,Receitas Correntes,Outras Receitas Correntes,"Bens, Direitos e Valores Incorporados ao Patr",REC.DIVIDA ATIVA NAO TRIBUTARIA DE OUTRAS REC,0.0,0.0,1297.13,0.0,2013-12-31,2013
1,Advocacia-Geral da União,63000,Advocacia-Geral da União - Unidades com víncul...,110060,COORD. GERAL DE ORC. FIN. E ANAL. CONT. - AGU,Receitas Correntes,Outras Receitas Correntes,"Indenizações, restituições e ressarcimentos",RECUPERACAO DE DESPESAS DE EXERC. ANTERIORES,0.0,0.0,26666621.42,0.0,2013-12-31,2013

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1026299 entries, 0 to 134592
Data columns (total 15 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   NOMBRE ÓRGANO SUPERIOR      1026299 non-null  object
 1   CÓDIGO ÓRGANO               1026299 non-null  int64
 2   NOMBRE ÓRGANO               1026299 non-null  object
 3   CÓDIGO UNIDAD GESTORA       1026299 non-null  int64
 4   NOMBRE UNIDAD GESTORA       1026299 non-null  object
 5   CATEGORÍA ECONÓMICA         1026299 non-null  object
 6   ORIGEN INGRESO              1026299 non-null  object
 7   TIPO INGRESO                1026299 non-null  object
 8   DETALLE                     1026299 non-null  object
 9   VALOR PREVISTO ACTUALIZADO  1026299 non-null  float64
 10  VALOR LANZADO               1026299 non-null  float64
 11  VALOR REALIZADO             1026299 non-null  float64
 12  PORCENTAJE REALIZADO        1026299 non-null  float64
 13  FECHA LANZAMIENTO           1026299 non-null  object
 14  AÑO EJERCICIO               1026299 non-null  int64
dtypes: float64(4), int64(3), object(8)
memory usage: 125.3+ MB

In [35]:
df["FECHA LANZAMIENTO"] = pd.to_datetime(df["FECHA LANZAMIENTO"], format="mixed")

In [60]:
df["AÑO EJERCICIO"] = pd.to_datetime(df["AÑO EJERCICIO"], format= '%Y')

In [61]:
df["AÑO EJERCICIO"] = df["AÑO EJERCICIO"].dt.year

In [40]:
df.sample()

,NOMBRE ÓRGANO SUPERIOR,CÓDIGO ÓRGANO,NOMBRE ÓRGANO,CÓDIGO UNIDAD GESTORA,NOMBRE UNIDAD GESTORA,CATEGORÍA ECONÓMICA,ORIGEN INGRESO,TIPO INGRESO,DETALLE,VALOR PREVISTO ACTUALIZADO,VALOR LANZADO,VALOR REALIZADO,PORCENTAJE REALIZADO,FECHA LANZAMIENTO,AÑO EJERCICIO
147738,Ministério da Saúde,36212,Agência Nacional de Vigilância Sanitária,253002,AGENCIA NACIONAL DE VIGILANCIA SANITARIA,Receitas Correntes,Receita de Serviços,Serviços Administrativos e Comerciais Gerais,SERV.ADMINISTRAT.E COMERCIAIS GERAIS-PRINC.,0.0,0.0,11.2,0.0,2018-11-23,2018

In [62]:
df.to_csv("../11.Proyecto2_EDA-Ingresos-Publicos-Brasil/datos/datos-unidos.csv", index=False, encoding='latin-1')

In [63]:
df.to_pickle("../11.Proyecto2_EDA-Ingresos-Publicos-Brasil/datos/datos-unidos.pkl")

In [64]:
df.sample(2)

,NOMBRE ÓRGANO SUPERIOR,CÓDIGO ÓRGANO,NOMBRE ÓRGANO,CÓDIGO UNIDAD GESTORA,NOMBRE UNIDAD GESTORA,CATEGORÍA ECONÓMICA,ORIGEN INGRESO,TIPO INGRESO,DETALLE,VALOR PREVISTO ACTUALIZADO,VALOR LANZADO,VALOR REALIZADO,PORCENTAJE REALIZADO,FECHA LANZAMIENTO,AÑO EJERCICIO
164662,Ministério das Comunicações,41232,Fundo de Universalização dos Serviços de Telec...,413047,FUNDO DE UNIVERS.DOS SERV.TELECOMUNICACOES,Receitas Correntes,Receita Patrimonial,Delegação de Serviços Públicos Mediante Conce,DELEG.SERV.TELEC.-POD.CONC.NO REG.PUB.-PRINC.,0.0,0.0,642.73,0.0,2017-04-19,2017
110200,Ministério da Saúde,36000,Ministério da Saúde - Unidades com vínculo direto,250088,SPO-COORD.-GERAL DE ORC.E FINANCAS/MS,Receitas Correntes,Receita de Serviços,Serviços Administrativos e Comerciais Gerais,SERV.ADMINISTRAT.E COMERCIAIS GERAIS-PRINC.,0.0,0.0,45.20,0.0,2021-04-20,2021

In [65]:
sl.reporte(df)

                            numero_nulos  porcentaje_nulos  tipo_variables
NOMBRE ÓRGANO SUPERIOR                 0               0.0          object
CÓDIGO ÓRGANO                          0               0.0           int64
NOMBRE ÓRGANO                          0               0.0          object
CÓDIGO UNIDAD GESTORA                  0               0.0           int64
NOMBRE UNIDAD GESTORA                  0               0.0          object
CATEGORÍA ECONÓMICA                    0               0.0          object
ORIGEN INGRESO                         0               0.0          object
TIPO INGRESO                           0               0.0          object
DETALLE                                0               0.0          object
VALOR PREVISTO ACTUALIZADO             0               0.0         float64
VALOR LANZADO                          0               0.0         float64
VALOR REALIZADO                        0               0.0         float64
PORCENTAJE REALIZADO                   0               0.0         float64
FECHA LANZAMIENTO                      0               0.0  datetime64[ns]
AÑO EJERCICIO                          0               0.0           int32

In [66]:
df.columns

Index(['NOMBRE ÓRGANO SUPERIOR', 'CÓDIGO ÓRGANO', 'NOMBRE ÓRGANO',
       'CÓDIGO UNIDAD GESTORA', 'NOMBRE UNIDAD GESTORA', 'CATEGORÍA ECONÓMICA',
       'ORIGEN INGRESO', 'TIPO INGRESO', 'DETALLE',
       'VALOR PREVISTO ACTUALIZADO', 'VALOR LANZADO', 'VALOR REALIZADO',
       'PORCENTAJE REALIZADO', 'FECHA LANZAMIENTO', 'AÑO EJERCICIO'],
      dtype='object')